[program:ehd]
command=python3 /opt/eh/ehd/ehd.py
autorestart=true
startsecs=1
stdout_logfile=/var/log/eh/ehd.log
stderr_logfile=/var/log/eh/ehd.err.log

[program:eh-bootstrap]
command=/opt/eh/container/bootstrap-server.sh
autorestart=false
startretries=0
stdout_logfile=/var/log/eh/bootstrap.log
stderr_logfile=/var/log/eh/bootstrap.err.log
