[supervisord]
nodaemon=true
user=root
logfile=/var/log/eh/supervisord.log
pidfile=/run/eh/supervisord.pid

[unix_http_server]
file=/run/eh/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/eh/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
